remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'Docs':
    - 'https://jacob-alford.github.io/schemable-ts-types/'
  'Docs':
    - 'https://jacob-alford.github.io/schemable-ts-types/modules'
  "GitHub":
    - "https://github.com/jacob-alford/schemable-ts-types"
